from __future__ import annotations
import json,os,subprocess,sys,tempfile,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PY=sys.executable
PREP=ROOT/"scripts"/"prepare_jnu_cloud_request_v1_1.py";BRIDGE=ROOT/"scripts"/"build_jnu_private_entitled_quote_bundle_v1.py";LAUNCH=ROOT/"scripts"/"launch_jnu_private_entitled_forecast_v1.py";OUTCOME=ROOT/"scripts"/"record_jnu_private_entitled_outcome_v1.py";SCORER=ROOT/"scripts"/"score_jnu_private_entitled_live_shadow_v1.py";RECOVERY=ROOT/"scripts"/"recover_jnu_private_entitled_ledger_v1.py";RETENTION=ROOT/"scripts"/"retain_jnu_private_entitled_ledger_v1.py";VALID=ROOT/"scripts"/"validate_jnu_private_launch_manifest_v1.py"
RFD=ROOT/"live_shadow"/"forecasts";ROD=ROOT/"live_shadow"/"outcomes"
def counts():return (len(list(RFD.glob("*.json"))) if RFD.exists() else 0,len(list(ROD.glob("*.json"))) if ROD.exists() else 0)
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+"\n")
def draft():
 return {"draft_id":"JNU_DRAFT_20260907T080930_LIFECYCLE","analysis_frozen_at_taipei":"2026-09-07T08:09:30+08:00","symbol":"NK225MCU2026","target_day_session_date":"2026-09-07","decision_input":{"blocks":[{"id":"EXACT_JNU_PRICE_PATH","vote":"BEARISH","quality":"A","reason":"synthetic"},{"id":"DYNAMIC_PRICE_DISCOVERY","vote":"NEUTRAL","quality":"B","reason":"synthetic"},{"id":"CONTEMPORANEOUS_CROSS_MARKET","vote":"BEARISH","quality":"B","reason":"synthetic"},{"id":"POSITIONING_DERIVATIVES_CONTEXT","vote":"NEUTRAL","quality":"B","reason":"synthetic"}],"risk_modifiers":{"volatility_state":"UNKNOWN","event_state":"AUTO_OFFICIAL","sq_state":"UNKNOWN","post_event_exact_jnu_path_available":False}},"expected_path":"synthetic","key_levels":[65000],"invalidation_conditions":"synthetic","event_risk":"synthetic","flip_conditions":"synthetic","evidence_summary":"lifecycle"}
def event():
 checked="2026-09-07T08:09:45+08:00";names=["BOJ_RELEASE_SCHEDULE","JAPAN_STAT_CPI","JAPAN_STAT_LABOUR_FORCE","JAPAN_STAT_HOUSEHOLD_SPENDING","JAPAN_ESRI_GENERAL","JAPAN_ESRI_GDP","US_BLS_HIGH_IMPACT_SCHEDULE_COVERAGE","US_BEA_RELEASE_SCHEDULE","FEDERAL_RESERVE_CALENDAR"];src=[{"source":n,"reference":"https://official.example/"+n,"checked_at_taipei":checked,"http_status":200,"parsed_event_count":1} for n in names]
 return {"version":"1.1","status":"OFFICIAL_EVENT_STATE_READY","protocol":"config/jnu_official_event_state_protocol_v1_1.json","evaluated_at_taipei":checked,"target_day_session_date":"2026-09-07","event_state":"NORMAL","risk_state_evidence":{"checked_at_taipei":checked,"target_day_session_date":"2026-09-07","event_state":"NORMAL","volatility_state":"UNKNOWN","sq_state":"UNKNOWN","event_sources":src},"future_high_events":[],"past_high_events":[],"ambiguous_date_only_high_events":[],"source_failures":[],"all_parsed_events":[],"decision_risk_modifiers":{"volatility_state":"UNKNOWN","event_state":"NORMAL","sq_state":"UNKNOWN","post_event_exact_jnu_path_available":False},"real_registration_performed":False}
def ev(price,ts):
 return {"entitlement_mode":"OSE_FREE_TRIAL","provider_name":"SYNTH","entitlement_reference":"opaque","transport_qualification_id":"q1","positive_margin_demonstrated":True,"canonical_symbol":"NK225MCU2026","exchange":"OSE","product":"Nikkei 225 micro Futures","contract_month":"2026-09","price":price,"tick_size":5,"provider_timestamp":ts,"observed_at_taipei":"2026-09-07T08:05:30+08:00","exact_product":True,"continuous_contract":False,"broker_login_used":False,"trading_permission_used":False,"order_capable_session_used":False,"identity_evidence":{"exchange":"OSE","product":"Nikkei 225 micro Futures","contract_month":"2026-09","provider_symbol":"MC225U26"},"storage_scope":"PRIVATE_INTERNAL_ONLY","evidence_destination_class":"PRIVATE_INTERNAL_STORE","raw_public_distribution_permitted":False,"public_derived_permission_status":"UNCONFIRMED","third_party_cloud_processing_used":False,"third_party_cloud_permission_status":"NOT_APPLICABLE"}
PM={"entitlement_mode":"OSE_FREE_TRIAL","raw_evidence_storage_scope":"PRIVATE_INTERNAL_ONLY","evidence_destination_class":"PRIVATE_INTERNAL_STORE","target_repository_visibility":"PRIVATE","raw_market_data_in_public_artifact":False,"third_party_cloud_processing_used":False,"third_party_cloud_permission_status":"NOT_APPLICABLE","public_output_requested":False,"public_output_type":"NONE","public_publication_permission_status":"UNCONFIRMED","reconstructive_market_data_fields_in_public_output":False}
before=counts();T={}
with tempfile.TemporaryDirectory(prefix="jnu_lifecycle_ext_") as td0:
 td=Path(td0);ledger=td/"ledger";qstore=td/"qstore";manifest=td/"launch.json"
 LM={"version":"1.0","launch_id":"JNU_PRIV_LAUNCH_SYNTH_20260908","mode":"SYNTHETIC","synthetic_data_only":True,"real_entitlement_connected":False,"private_ledger_root":str(ledger),"private_quote_store_root":str(qstore),"public_output_requested":False,"cloud_processing_used":False,"cloud_permission_status":"NOT_APPLICABLE","publication_permission_status":"UNCONFIRMED","retention_terms_status":"SYNTHETIC_TEST_ONLY","retention_policy_status":"SYNTHETIC_TEST_APPROVED","retention_days":30,"recovery_apply_allowed":True,"retention_quarantine_enabled":True,"permanent_purge_allowed":False};write(manifest,LM)
 cp=subprocess.run([PY,str(VALID),"--manifest",str(manifest)],cwd=ROOT,capture_output=True,text=True);T["launch_manifest_pass"]=cp.returncode==0
 bad=td/"badreal.json";x=dict(LM);x.update({"launch_id":"JNU_PRIV_LAUNCH_REAL_20260908","mode":"REAL_ENTITLED","synthetic_data_only":False,"real_entitlement_connected":True});write(bad,x)
 cp=subprocess.run([PY,str(VALID),"--manifest",str(bad)],cwd=ROOT,capture_output=True,text=True);T["real_manifest_without_approval_rejected"]=cp.returncode!=0
 dp=td/"d.json";ep=td/"e.json";rp=td/"request.json";write(dp,draft());write(ep,event());cp=subprocess.run([PY,str(PREP),"--draft",str(dp),"--output",str(rp),"--selftest","--event-evidence-file",str(ep),"--request-created-at-taipei","2026-09-07T08:10:00+08:00"],cwd=ROOT,capture_output=True,text=True);T["request_pass"]=cp.returncode==0
 pm=td/"pm.json";qe=td/"quote.json";write(pm,PM);write(qe,ev(65000,"2026-09-07T09:05:00+09:00"));cp=subprocess.run([PY,str(BRIDGE),"--evidence",str(qe),"--permission-manifest",str(pm),"--private-store-root",str(qstore)],cwd=ROOT,capture_output=True,text=True);T["quote_bridge_pass"]=cp.returncode==0;qb=next((qstore/"quote_receipts").glob("*.json"))
 cmd=[PY,str(LAUNCH),"--manifest",str(manifest),"--request",str(rp),"--private-quote-bundle",str(qb),"--created-at-taipei","2026-09-07T08:10:30+08:00"];cp=subprocess.run(cmd,cwd=ROOT,capture_output=True,text=True);T["first_forecast_pass"]=cp.returncode==0;fid=json.loads(cp.stdout)["forecast_id"]
 cp2=subprocess.run(cmd,cwd=ROOT,capture_output=True,text=True);T["forecast_exact_replay_idempotent"]=cp2.returncode==0 and json.loads(cp2.stdout)["registration_status"]=="PRIVATE_ENTITLED_FORECAST_ALREADY_REGISTERED" and len(list((ledger/"forecasts").glob("*.json")))==1
 qe2=td/"quote2.json";write(qe2,ev(65005,"2026-09-07T09:05:00+09:00"));qstore2=td/"qstore2";cp=subprocess.run([PY,str(BRIDGE),"--evidence",str(qe2),"--permission-manifest",str(pm),"--private-store-root",str(qstore2)],cwd=ROOT,capture_output=True,text=True);qb2=next((qstore2/"quote_receipts").glob("*.json"));cp=subprocess.run([PY,str(LAUNCH),"--manifest",str(manifest),"--request",str(rp),"--private-quote-bundle",str(qb2),"--created-at-taipei","2026-09-07T08:10:30+08:00"],cwd=ROOT,capture_output=True,text=True);T["forecast_conflict_rejected"]=cp.returncode!=0
 fp=ledger/"forecasts"/f"{fid}.json";T["forecast_backup_present"]=(ledger/"recovery"/"backups"/"forecasts"/f"{fid}.json").exists()
 ce=td/"close.json";write(ce,ev(64000,"2026-09-07T15:45:00+09:00"));ocmd=[PY,str(OUTCOME),"--private-ledger-root",str(ledger),"--forecast-id",fid,"--private-close-evidence",str(ce)];cp=subprocess.run(ocmd,cwd=ROOT,capture_output=True,text=True);T["first_outcome_pass"]=cp.returncode==0
 cp2=subprocess.run(ocmd,cwd=ROOT,capture_output=True,text=True);T["outcome_exact_replay_idempotent"]=cp2.returncode==0 and json.loads(cp2.stdout)["status"]=="PRIVATE_ENTITLED_OUTCOME_ALREADY_RECORDED"
 ce2=td/"close2.json";write(ce2,ev(64005,"2026-09-07T15:45:00+09:00"));cp=subprocess.run([PY,str(OUTCOME),"--private-ledger-root",str(ledger),"--forecast-id",fid,"--private-close-evidence",str(ce2)],cwd=ROOT,capture_output=True,text=True);T["outcome_conflict_rejected"]=cp.returncode!=0
 score=ledger/"results"/"score.json";cp=subprocess.run([PY,str(SCORER),"--private-ledger-root",str(ledger),"--output",str(score)],cwd=ROOT,capture_output=True,text=True);T["scorer_checkpoint_pass"]=cp.returncode==0 and (ledger/"results"/"private_live_shadow_checkpoint_v1.json").exists()
 original=fp.read_bytes();x=json.loads(fp.read_text());x["reference_price"]=65100;write(fp,x);cp=subprocess.run([PY,str(RECOVERY),"--manifest",str(manifest)],cwd=ROOT,capture_output=True,text=True);T["corruption_detected"]=cp.returncode==4
 cp=subprocess.run([PY,str(RECOVERY),"--manifest",str(manifest),"--apply"],cwd=ROOT,capture_output=True,text=True);T["corruption_restored"]=cp.returncode==0 and fp.read_bytes()==original
 op=ledger/"outcomes"/f"{fid}.json";op.unlink();cp=subprocess.run([PY,str(RECOVERY),"--manifest",str(manifest),"--apply"],cwd=ROOT,capture_output=True,text=True);T["missing_outcome_restored"]=cp.returncode==0 and op.exists()
 tmp=ledger/"forecasts"/".crash.tmp-test";tmp.write_text("partial");cp=subprocess.run([PY,str(RECOVERY),"--manifest",str(manifest),"--apply"],cwd=ROOT,capture_output=True,text=True);T["temp_quarantined"]=cp.returncode==0 and not tmp.exists()
 old=time.time()-40*86400
 for p in [fp,op]:os.utime(p,(old,old))
 cp=subprocess.run([PY,str(RETENTION),"--manifest",str(manifest),"--now-taipei","2026-10-20T12:00:00+08:00","--apply"],cwd=ROOT,capture_output=True,text=True);T["completed_pair_quarantined"]=cp.returncode==0 and not fp.exists() and not op.exists() and len(list((ledger/"retention_quarantine"/"completed").iterdir()))==1
 T["no_permanent_purge"]=json.loads(cp.stdout)["permanent_purge_performed"] is False
after=counts();T["public_ledger_untouched"]=before==after==(0,0)
status="PASS" if all(T.values()) else "FAIL";print(json.dumps({"status":status,"tests":T,"passed":sum(T.values()),"total":len(T),"public_ledger_before":before,"public_ledger_after":after},indent=2));raise SystemExit(0 if status=="PASS" else 1)
