from __future__ import annotations
import json,os,subprocess,sys,tempfile,time
from datetime import datetime,timezone,timedelta
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PY=sys.executable
PREP=ROOT/"scripts"/"prepare_jnu_cloud_request_v1_1.py";BRIDGE=ROOT/"scripts"/"build_jnu_private_entitled_quote_bundle_v1.py";LAUNCH=ROOT/"scripts"/"launch_jnu_private_entitled_forecast_v1.py";OUT=ROOT/"scripts"/"record_jnu_private_entitled_outcome_v1.py";SCORE=ROOT/"scripts"/"score_jnu_private_entitled_live_shadow_v1.py";STATE=ROOT/"scripts"/"jnu_private_launch_state_v1.py";LOCK=ROOT/"scripts"/"jnu_private_lock_v1.py";REC=ROOT/"scripts"/"recover_jnu_private_entitled_ledger_v1.py";EXP=ROOT/"scripts"/"export_jnu_private_backupset_v1.py";IMP=ROOT/"scripts"/"import_jnu_private_backupset_v1.py"
RFD=ROOT/"live_shadow"/"forecasts";ROD=ROOT/"live_shadow"/"outcomes"
def counts():return (len(list(RFD.glob("*.json"))) if RFD.exists() else 0,len(list(ROD.glob("*.json"))) if ROD.exists() else 0)
def w(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+"\n")
def draft():
 return {"draft_id":"JNU_DRAFT_20260907T080930_DRSTATE","analysis_frozen_at_taipei":"2026-09-07T08:09:30+08:00","symbol":"NK225MCU2026","target_day_session_date":"2026-09-07","decision_input":{"blocks":[{"id":"EXACT_JNU_PRICE_PATH","vote":"BEARISH","quality":"A","reason":"synthetic"},{"id":"DYNAMIC_PRICE_DISCOVERY","vote":"NEUTRAL","quality":"B","reason":"synthetic"},{"id":"CONTEMPORANEOUS_CROSS_MARKET","vote":"BEARISH","quality":"B","reason":"synthetic"},{"id":"POSITIONING_DERIVATIVES_CONTEXT","vote":"NEUTRAL","quality":"B","reason":"synthetic"}],"risk_modifiers":{"volatility_state":"UNKNOWN","event_state":"AUTO_OFFICIAL","sq_state":"UNKNOWN","post_event_exact_jnu_path_available":False}},"expected_path":"synthetic","key_levels":[65000],"invalidation_conditions":"synthetic","event_risk":"synthetic","flip_conditions":"synthetic","evidence_summary":"drstate"}
def event():
 checked="2026-09-07T08:09:45+08:00";names=["BOJ_RELEASE_SCHEDULE","JAPAN_STAT_CPI","JAPAN_STAT_LABOUR_FORCE","JAPAN_STAT_HOUSEHOLD_SPENDING","JAPAN_ESRI_GENERAL","JAPAN_ESRI_GDP","US_BLS_HIGH_IMPACT_SCHEDULE_COVERAGE","US_BEA_RELEASE_SCHEDULE","FEDERAL_RESERVE_CALENDAR"];src=[{"source":n,"reference":"https://official.example/"+n,"checked_at_taipei":checked,"http_status":200,"parsed_event_count":1} for n in names]
 return {"version":"1.1","status":"OFFICIAL_EVENT_STATE_READY","protocol":"config/jnu_official_event_state_protocol_v1_1.json","evaluated_at_taipei":checked,"target_day_session_date":"2026-09-07","event_state":"NORMAL","risk_state_evidence":{"checked_at_taipei":checked,"target_day_session_date":"2026-09-07","event_state":"NORMAL","volatility_state":"UNKNOWN","sq_state":"UNKNOWN","event_sources":src},"future_high_events":[],"past_high_events":[],"ambiguous_date_only_high_events":[],"source_failures":[],"all_parsed_events":[],"decision_risk_modifiers":{"volatility_state":"UNKNOWN","event_state":"NORMAL","sq_state":"UNKNOWN","post_event_exact_jnu_path_available":False},"real_registration_performed":False}
def ev(price,ts,obs):
 return {"entitlement_mode":"OSE_FREE_TRIAL","provider_name":"SYNTH","entitlement_reference":"opaque","transport_qualification_id":"q1","positive_margin_demonstrated":True,"canonical_symbol":"NK225MCU2026","exchange":"OSE","product":"Nikkei 225 micro Futures","contract_month":"2026-09","price":price,"tick_size":5,"provider_timestamp":ts,"observed_at_taipei":obs,"exact_product":True,"continuous_contract":False,"broker_login_used":False,"trading_permission_used":False,"order_capable_session_used":False,"identity_evidence":{"exchange":"OSE","product":"Nikkei 225 micro Futures","contract_month":"2026-09","provider_symbol":"MC225U26"},"storage_scope":"PRIVATE_INTERNAL_ONLY","evidence_destination_class":"PRIVATE_INTERNAL_STORE","raw_public_distribution_permitted":False,"public_derived_permission_status":"UNCONFIRMED","third_party_cloud_processing_used":False,"third_party_cloud_permission_status":"NOT_APPLICABLE"}
PM={"entitlement_mode":"OSE_FREE_TRIAL","raw_evidence_storage_scope":"PRIVATE_INTERNAL_ONLY","evidence_destination_class":"PRIVATE_INTERNAL_STORE","target_repository_visibility":"PRIVATE","raw_market_data_in_public_artifact":False,"third_party_cloud_processing_used":False,"third_party_cloud_permission_status":"NOT_APPLICABLE","public_output_requested":False,"public_output_type":"NONE","public_publication_permission_status":"UNCONFIRMED","reconstructive_market_data_fields_in_public_output":False}
before=counts();T={}
with tempfile.TemporaryDirectory(prefix="jnu_drstate_ext_") as td0:
 td=Path(td0);ledger=td/"ledger";qstore=td/"qstore";manifest=td/"launch.json";backuproot=td/"backupsets"
 LM={"version":"1.0","launch_id":"JNU_PRIV_LAUNCH_DRSTATE_20260908","mode":"SYNTHETIC","synthetic_data_only":True,"real_entitlement_connected":False,"private_ledger_root":str(ledger),"private_quote_store_root":str(qstore),"public_output_requested":False,"cloud_processing_used":False,"cloud_permission_status":"NOT_APPLICABLE","publication_permission_status":"UNCONFIRMED","retention_terms_status":"SYNTHETIC_TEST_ONLY","retention_policy_status":"SYNTHETIC_TEST_APPROVED","retention_days":30,"recovery_apply_allowed":True,"retention_quarantine_enabled":True,"permanent_purge_allowed":False};w(manifest,LM)
 dp=td/"d.json";ep=td/"e.json";rp=td/"request.json";w(dp,draft());w(ep,event());cp=subprocess.run([PY,str(PREP),"--draft",str(dp),"--output",str(rp),"--selftest","--event-evidence-file",str(ep),"--request-created-at-taipei","2026-09-07T08:10:00+08:00"],cwd=ROOT,capture_output=True,text=True);T["request_pass"]=cp.returncode==0
 pm=td/"pm.json";qe=td/"quote.json";w(pm,PM);w(qe,ev(65000,"2026-09-07T09:05:00+09:00","2026-09-07T08:05:30+08:00"));cp=subprocess.run([PY,str(BRIDGE),"--evidence",str(qe),"--permission-manifest",str(pm),"--private-store-root",str(qstore)],cwd=ROOT,capture_output=True,text=True);T["quote_bridge_pass"]=cp.returncode==0;qb=next((qstore/"quote_receipts").glob("*.json"))
 p1=subprocess.Popen([PY,str(LAUNCH),"--manifest",str(manifest),"--request",str(rp),"--private-quote-bundle",str(qb),"--created-at-taipei","2026-09-07T08:10:30+08:00"],cwd=ROOT,stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True)
 p2=subprocess.Popen([PY,str(LAUNCH),"--manifest",str(manifest),"--request",str(rp),"--private-quote-bundle",str(qb),"--created-at-taipei","2026-09-07T08:10:30+08:00"],cwd=ROOT,stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True)
 o1,e1=p1.communicate();o2,e2=p2.communicate();T["concurrent_launch_both_safe"]=p1.returncode==0 and p2.returncode==0 and len(list((ledger/"forecasts").glob("*.json")))==1
 sts=sorted([json.loads(o1)["registration_status"],json.loads(o2)["registration_status"]]);T["concurrent_exactly_one_write"]=sts==["PRIVATE_ENTITLED_FORECAST_ALREADY_REGISTERED","PRIVATE_ENTITLED_FORECAST_REGISTERED"]
 fid=json.loads(o1)["forecast_id"];sp=ledger/"launch_states"/f"{LM['launch_id']}.json";st=json.loads(sp.read_text());T["state_after_launch_outcome_pending"]=st["current_state"]=="OUTCOME_PENDING" and [x["state"] for x in st["history"]][:4]==["PREPARED","QUOTE_BOUND","FORECASTED","OUTCOME_PENDING"]
 holder=subprocess.Popen([PY,str(LOCK),"--root",str(ledger),"--key","concurrency-test","--hold-seconds","0.6","--lease-seconds","5","--wait-seconds","0"],cwd=ROOT,stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True);time.sleep(0.15)
 cp=subprocess.run([PY,str(LOCK),"--root",str(ledger),"--key","concurrency-test","--wait-seconds","0.1"],cwd=ROOT,capture_output=True,text=True);T["active_lock_blocks_second_process"]=cp.returncode!=0 and "PRIVATE_LOCK_BUSY" in cp.stderr;holder.communicate()
 lp=ledger/".locks"/(__import__("hashlib").sha256(b"stale-test").hexdigest()+".json");lp.parent.mkdir(parents=True,exist_ok=True);past=(datetime.now(timezone.utc)-timedelta(seconds=10));w(lp,{"owner_token":"dead","pid":999999,"hostname":"synthetic","acquired_at_utc":(past-timedelta(seconds=5)).isoformat(),"lease_expires_at_utc":past.isoformat(),"key_sha256":__import__("hashlib").sha256(b"stale-test").hexdigest()})
 cp=subprocess.run([PY,str(REC),"--manifest",str(manifest)],cwd=ROOT,capture_output=True,text=True);T["stale_lock_detected"]=cp.returncode==4 and json.loads(cp.stdout)["stale_lock_count"]==1
 cp=subprocess.run([PY,str(REC),"--manifest",str(manifest),"--apply"],cwd=ROOT,capture_output=True,text=True);T["stale_lock_quarantined"]=cp.returncode==0 and not lp.exists()
 ce=td/"close.json";w(ce,ev(64000,"2026-09-07T15:45:00+09:00","2026-09-07T14:45:30+08:00"));cp=subprocess.run([PY,str(OUT),"--private-ledger-root",str(ledger),"--forecast-id",fid,"--private-close-evidence",str(ce)],cwd=ROOT,capture_output=True,text=True);T["outcome_pass"]=cp.returncode==0
 cp=subprocess.run([PY,str(STATE),"--manifest",str(manifest),"--request",str(rp),"--private-quote-bundle",str(qb)],cwd=ROOT,capture_output=True,text=True);T["state_after_outcome"]=cp.returncode==0 and json.loads(cp.stdout)["current_state"]=="OUTCOME_RECORDED"
 score=ledger/"results"/"score.json";cp=subprocess.run([PY,str(SCORE),"--private-ledger-root",str(ledger),"--output",str(score)],cwd=ROOT,capture_output=True,text=True);T["score_pass"]=cp.returncode==0
 cp=subprocess.run([PY,str(STATE),"--manifest",str(manifest),"--request",str(rp),"--private-quote-bundle",str(qb)],cwd=ROOT,capture_output=True,text=True);T["state_scored"]=cp.returncode==0 and json.loads(cp.stdout)["current_state"]=="SCORED"
 cp=subprocess.run([PY,str(EXP),"--manifest",str(manifest),"--destination-root",str(backuproot),"--backupset-id","JNU_PRIV_BACKUP_DRSTATE"],cwd=ROOT,capture_output=True,text=True);T["backup_export_pass"]=cp.returncode==0;bs=backuproot/"JNU_PRIV_BACKUP_DRSTATE"
 badroot=td/"badbackup";__import__("shutil").copytree(bs,badroot);payloads=list((badroot/"payload").rglob("*.json"));payloads[0].write_bytes(payloads[0].read_bytes()+b"x");destbad=td/"restore_bad";cp=subprocess.run([PY,str(IMP),"--backupset",str(badroot),"--destination-ledger-root",str(destbad)],cwd=ROOT,capture_output=True,text=True);T["corrupt_backup_import_rejected"]=cp.returncode!=0
 dest=td/"restored";cp=subprocess.run([PY,str(IMP),"--backupset",str(bs),"--destination-ledger-root",str(dest)],cwd=ROOT,capture_output=True,text=True);T["dr_import_revalidated"]=cp.returncode==0 and (dest/"results"/"dr_revalidated_v1.json").exists()
 cp=subprocess.run([PY,str(IMP),"--backupset",str(bs),"--destination-ledger-root",str(dest)],cwd=ROOT,capture_output=True,text=True);T["nonempty_import_rejected"]=cp.returncode!=0
 LM2=dict(LM);LM2["private_ledger_root"]=str(dest);m2=td/"launch_restored.json";w(m2,LM2);cp=subprocess.run([PY,str(STATE),"--manifest",str(m2),"--request",str(rp)],cwd=ROOT,capture_output=True,text=True);T["state_reconstructed_after_dr"]=cp.returncode==0 and json.loads(cp.stdout)["current_state"]=="SCORED"
after=counts();T["public_ledger_untouched"]=before==after==(0,0)
status="PASS" if all(T.values()) else "FAIL";print(json.dumps({"status":status,"tests":T,"passed":sum(T.values()),"total":len(T),"public_ledger_before":before,"public_ledger_after":after},indent=2));raise SystemExit(0 if status=="PASS" else 1)
